# Generated by Django 2.2.4 on 2020-04-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account_details',
            name='account_number',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user_tax_details',
            name='opening_balance',
            field=models.CharField(blank=True, db_index=True, default=0.0, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user_tax_details',
            name='tds',
            field=models.IntegerField(blank=True, db_index=True, default=0.0, null=True),
        ),
    ]
