# Generated by Django 2.2.4 on 2020-04-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200404_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_address_details',
            old_name='is_billing_address_diff',
            new_name='is_shipping_address_diff',
        ),
    ]
