# Generated by Django 2.2.4 on 2020-03-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200331_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address_details',
            name='is_billing_address',
            field=models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='is_shipping_address',
            field=models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True, null=True),
        ),
    ]
