# Generated by Django 2.2.4 on 2020-04-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200403_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tax_details',
            name='gst_reg_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'GST Registered-Regular'), (2, 'GST Registered-Composition,'), (3, 'GST unregistered'), (4, 'Consumer'), (5, 'Overseas'), (6, 'SEZ'), (7, 'Deemed Exports -EOU’s, STP’s , EHTP’s etc')], db_index=True, default=0, null=True),
        ),
    ]
