# Generated by Django 2.2.4 on 2020-04-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200404_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address_details',
            name='is_billing_address',
            field=models.IntegerField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='is_shipping_address',
            field=models.IntegerField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='is_shipping_address_diff',
            field=models.IntegerField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False),
        ),
    ]
