# Generated by Django 2.2.4 on 2020-03-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200331_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address_details',
            name='is_billing_address',
            field=models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='is_billing_address_diff',
            field=models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='is_shipping_address',
            field=models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, null=True),
        ),
    ]
