# Generated by Django 2.2.4 on 2020-04-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200404_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address_details',
            name='is_billing_address',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='is_shipping_address',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='is_shipping_address_diff',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True),
        ),
    ]
