# Generated by Django 2.2.4 on 2020-04-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bundleproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleproducts',
            name='quantity',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='cost_price',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='gst',
            field=models.IntegerField(blank=True, db_index=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='selling_price',
            field=models.IntegerField(blank=True, db_index=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='tax',
            field=models.IntegerField(blank=True, db_index=True, default=0.0, null=True),
        ),
    ]
