# Generated by Django 2.2.4 on 2020-04-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200402_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='is_purchase',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='is_sales',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='manufactured_date',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='marked_price',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='product_dimension',
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='is_billing_address',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='is_shipping_address',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False),
        ),
    ]
