# Generated by Django 3.0.2 on 2020-04-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200402_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='gst',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
    ]
