# Generated by Django 2.2.4 on 2020-04-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200404_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='purchase_account',
            field=models.IntegerField(blank=True, choices=[(0, 'Discount'), (1, 'General Income'), (2, 'Interest Income'), (3, 'Late Fee Income'), (4, 'Other Charges'), (5, 'Sales'), (6, 'Shipping Charges')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='sales_account',
            field=models.IntegerField(blank=True, choices=[(0, 'Discount'), (1, 'General Income'), (2, 'Interest Income'), (3, 'Late Fee Income'), (4, 'Other Charges'), (5, 'Sales'), (6, 'Shipping Charges')], db_index=True, null=True),
        ),
    ]
